# Identidad del proyecto en SonarQube Cloud (valores de TU cuenta)
sonar.organization=ravilesl
sonar.projectKey=ravilesl_reportaudit-lab
sonar.projectName=reportaudit-lab

# Qué se analiza y cómo
sonar.sources=app
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
